### ISSUE TITLE
conflict with stable requirements or minimum-stability.

### ISSUE THREAD

**Issue by newscloud** [filipajdacic/yii2-twilio#1]
Hi, I'm getting this error now using your package - it used to work fine.

Problem 1
    - The requested package filipajdacic/yii2-twilio * is satisfiable by filipajdacic/yii2-twilio[dev-master] but these conflict with your requirements or minimum-stability.

1. So, before, it worked and I began getting this error:
Error
Class 'Services_Twilio' not found

I used this at that time:
"filipajdacic/yii2-twilio": "dev-master",

2. I switched to 
"filipajdacic/yii2-twilio": "*",

Now, I get     - The requested package filipajdacic/yii2-twilio * is satisfiable by filipajdacic/yii2-twilio[dev-master] but these conflict with your requirements or minimum-stability.
 on composer update.

I tried moving this into 
"require-dev": {...}

but still get the error.

Also seeing this when I try to change to "*"
Problem 1
    - Installation request for filipajdacic/yii2-twilio * -> satisfiable by filipajdacic/yii2-twilio[dev-master].
    - Removal request for filipajdacic/yii2-twilio == 9999999-dev

**Comment by filipajdacic** [comment]
Hello @newscloud ,

Twillio has changed his PHP SDK, so I needed to make some changes to the component.

Now, everything should be okay, try to install extension with following command:

`php composer.phar require --prefer-dist filipajdacic/yii2-twilio "master@dev"`

After that, you can send SMS messages and etc. on the following way:
```

    $twilioService = Yii::$app->Yii2Twilio->initTwilio();
     try {
            $message = $twilioService->account->messages->create(array(
                "From" => "+12345678901", // From a valid Twilio number
                "To" => "+12345678901",   // Text this number
                "Body" => "Hello from my Yii2 Application!",
            ));
        } catch (\Twilio\Exceptions\RestException $e) {
                echo $e->getMessage();
        }
```

Just make sure that you have previously included extension in your config file..

Please give me a feedback if now works.

Thanks in advance.
Filip

**Comment by newscloud** [comment]
Thanks so much for responding. Unfortunately, it's still broken.

Returns this:
Twilio\Exceptions\RestException
[HTTP 400] Unable to create record: A 'From' phone number is required.

 $twilioService = Yii::$app->Yii2Twilio->initTwilio();
          try {
                 $message = $twilioService->account->messages->create(array(
                     "From" => "+1503676xxxx", // From a valid Twilio number
                     "To" => "+1507556xxxx",   // Text this number
                     "Body" => "Hello from my Yii2 Application!",
                 ));
             } catch (\Twilio\Exceptions\RestException $e) {
                     echo $e->getMessage();
             }

**Comment by filipajdacic** [comment]
@newscloud 

Try sending SMS with this and tell me if it works:

```
        $twilioService = Yii::$app->Yii2Twilio->initTwilio();
        try {
            $message = $twilioService->account->messages->create(
                "+12345678901", // To a number that you want to send sms
                array(
                "from" => "+12345678901",   // From a number that you are sending
                "body" => "Hello from my Yii2 Application!",
            ));
        } catch (\Twilio\Exceptions\RestException $e) {
                echo $e->getMessage();
        }
```

**Comment by newscloud** [comment]
Hi, thanks. That worked!

**Comment by paramessanjay** [comment]
hi am facing this error,
can any one help me out
Exception &#039;ReflectionException&#039; with message &#039;Class filipajdacic\yiitwilio\YiiTwilio does not exist&#039; 

in /opt/lampp/htdocs/test1/git/jetdesk/vendor/yiisoft/yii2/di/Container.php:415

i have done exactly which was in mentioned but it shoes class does not exist
